Repository tmax-cloud/kubevirt-image-service, pull requests merged in 2020-06, with the labels that each got.

#3 Enable github action
  .github/workflows/main.yml
  CONTRIBUTING.md
  README.md
  deploy/rook-ceph/cluster-test.yaml
  deploy/rook-ceph/common.yaml
  deploy/rook-ceph/operator.yaml
  deploy/rook-ceph/snapshotclass.yaml
  deploy/rook-ceph/storageclass-test.yaml
  docs/USERGUIDE.md
  docs/assets/kubevirt_image_service.png
  docs/assets/workflow.png
  hack/kube-registry.yaml
  tbox
  testbox
Labels: enhancement

#11 Fix to run CI pipeline on master push
  .github/workflows/main.yml
Labels: bug

#16 Implement a util function for condition array and apply condition array to VMI
  deploy/crds/hypercloud.tmaxanc.com_virtualmachineimages_crd.yaml
  deploy/crds/hypercloud.tmaxanc.com_virtualmachinevolumes_crd.yaml
  e2e/virtualmachinimage.go
  pkg/apis/hypercloud/v1alpha1/condition.go
  pkg/apis/hypercloud/v1alpha1/virtualmachineimage_types.go
  pkg/apis/hypercloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/virtualmachineimage/pvc.go
  pkg/controller/virtualmachineimage/pvc_test.go
  pkg/controller/virtualmachineimage/snapshot.go
  pkg/controller/virtualmachineimage/snapshot_test.go
  pkg/controller/virtualmachineimage/virtualmachineimage_controller.go
  pkg/controller/virtualmachinevolume/virtualmachinevolume_controller.go
  pkg/controller/virtualmachinevolume/virtualmachinevolume_controller_test.go
  pkg/util/condition.go
  pkg/util/condition_test.go
  pkg/util/util_suite_test.go
Labels: enhancement

#18 [BugFix] Modify to use accessMode RWO when creating scratch pvc
  e2e/virtualmachinimage.go
  pkg/controller/virtualmachineimage/scratch_pvc.go
Labels: bug

#9 VirtualMachineVolumeExport CRD
  dbox
  deploy/crds/hypercloud.tmaxanc.com_v1alpha1_virtualmachinevolumeexport_cr.yaml
  deploy/crds/hypercloud.tmaxanc.com_virtualmachinevolumeexports_crd.yaml
  deploy/role.yaml
  e2e/main_test.go
  e2e/virtualmachinevolumeexport.go
  pkg/apis/hypercloud/v1alpha1/virtualmachinevolumeexport_types.go
  pkg/apis/hypercloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_virtualmachinevolumeexport.go
  pkg/controller/virtualmachinevolumeexport/exporter_pod.go
  pkg/controller/virtualmachinevolumeexport/exporter_pod_test.go
  pkg/controller/virtualmachinevolumeexport/local_pod.go
  pkg/controller/virtualmachinevolumeexport/local_pod_test.go
  pkg/controller/virtualmachinevolumeexport/pvc.go
  pkg/controller/virtualmachinevolumeexport/pvc_test.go
  pkg/controller/virtualmachinevolumeexport/test_util.go
  pkg/controller/virtualmachinevolumeexport/virtualmachinevolumeexport_controller.go
  pkg/controller/virtualmachinevolumeexport/virtualmachinevolumeexport_suite_test.go
Labels: enhancement

#22 Downgrade operator-sdk version from v0.18.0 to v0.17.1
  deploy/crds/hypercloud.tmaxanc.com_virtualmachineimages_crd.yaml
  deploy/crds/hypercloud.tmaxanc.com_virtualmachinevolumeexports_crd.yaml
  deploy/crds/hypercloud.tmaxanc.com_virtualmachinevolumes_crd.yaml
  testbox
Labels: bug

#14 Add condition to VirtualMachineVolume status
  deploy/crds/hypercloud.tmaxanc.com_virtualmachinevolumes_crd.yaml
  e2e/virtualmachinevolume.go
  e2e/virtualmachinevolumeexport.go
  go.mod
  pkg/apis/hypercloud/v1alpha1/virtualmachinevolume_types.go
  pkg/apis/hypercloud/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/virtualmachinevolume/pvc.go
  pkg/controller/virtualmachinevolume/pvc_test.go
  pkg/controller/virtualmachinevolume/test_util.go
  pkg/controller/virtualmachinevolume/virtualmachinevolume_controller.go
  pkg/controller/virtualmachinevolume/virtualmachinevolume_controller_test.go
Labels: enhancement

#23 Change to deploy an container image when tag is created
  .github/workflows/main.yml
  .gitlab-ci.yml
Labels: enhancement

#17 [Documentation] Update Korean documentation to English
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/TROUBLESHOOTING.md
  docs/USERGUIDE.md
  docs/assets/workflow.png
  docs/assets/workflow_eng.png
Labels: documentation

#26 [Documentation] Add VirtualMachineExport section on user guide
  docs/USERGUIDE.md
Labels: documentation
